#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

pip install django_elasticsearch_dsl

python /app/manage.py makemigrations
python /app/manage.py migrate
python /app/manage.py runserver 0.0.0.0:8000
